source 'https://rubygems.org'

gem 'capybara', '~> 3.29' 
gem 'rspec', '~> 3.9' 
gem 'rubocop', '~> 0.78.0'
gem 'selenium-webdriver', '~> 3.142', '>= 3.142.6' 
gem 'launchy', '~> 2.4', '>= 2.4.3'
gem 'webdrivers', '~> 4.1', '>= 4.1.3'
gem 'ffi', '~> 1.11', '>= 1.11.3'
